Fix for vercel migration: Import alternative bcryptjs npm module
Error log:
2023-02-11T02:50:37.758Z	undefined	ERROR	Cannot find module '/var/task/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'
Require stack:
- /var/task/node_modules/bcrypt/bcrypt.js
- /var/task/controllers/userController.js
- /var/task/routes/userRoutes.js
- /var/task/index.js
- /var/task/___now_launcher.js
- /var/runtime/index.mjs
RequestId: 0223af22-ecc6-4f41-9871-f162386ef7a5 Error: Runtime exited with error: exit status 1
Runtime.ExitError

Solution:
- https://forum.serverless.com/t/after-making-a-deploy-i-test-the-function-and-show-this/8624
- https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#rhel-and-centos
- https://github.com/dcodeIO/bcrypt.js